version: '3'

services:
    app:
      build: .
      container_name: app
      command: ./.docker/entrypoint.sh
      tty: true
      volumes:
        - .:/home/python/app
      ports:
        - 8000:8000
      depends_on:
        - db

    db:
      build: .docker/postgres
      container_name: db
      tty: true
      volumes:
        - .docker/pgdata:/var/lib/postgresql/data
      environment:
        # - LC_ALL=pt_BR.UTF-8
        - POSTGRES_DB=invoice
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
      ports:
        - "5432:5432"

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      tty: true
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@user.com
        - PGADMIN_DEFAULT_PASSWORD=123456
      ports:
        - "9000:80"
      depends_on:
        - db

    zookeeper:
      image: confluentinc/cp-zookeeper:6.0.1
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        - ZOOKEEPER_CLIENT_PORT=2181
        - ZOOKEEPER_TICK_TIME=2000
    
    kafka:
      image: confluentinc/cp-kafka:6.0.1
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

    control-center:
      image: confluentinc/cp-enterprise-control-center:6.0.1
      container_name: control-center
      depends_on:
        - zookeeper
        - kafka
      ports:
        - "9021:9021"
      environment:
        - CONTROL_CENTER_ZOOKEEPER_CONNECT=zookeeper:2181
        - CONTROL_CENTER_BOOTSTRAP_SERVERS=kafka:9092
        - CONTROL_CENTER_REPLICATION_FACTOR=1
